name: Debug Build
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Install Dependencies
      run: msbuild -t:restore
    - name: Build Project
      run: msbuild AGG-Productions.sln /t:Build /p:Configuration=Debug
    - name: Resolve Short Commit Hash
      if: startsWith(github.ref, 'refs/tags/') == false
      id: get_hash
      shell: bash
      run: echo ::set-output name=hash::`git rev-parse --short HEAD`
    - name: Upload AGG-Productions Debug Build
      if: startsWith(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v2
      with:
        name: AGG-Productions-${{ steps.get_hash.outputs.hash }}
        path: ./bin/Debug/
    - name: Upload HTMLPlayer Debug Build
      if: startsWith(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v2
      with:
        name: HTMLPlayer-${{ steps.get_hash.outputs.hash }}
        path: ./HTMLPlayer/bin/Debug
